[project]
name = "loudest-office"
version = "0.1.0"
requires-python = "==3.14.7"
dependencies = [
    "ansible-builder==3.1.1",
    "ansible-lint==26.8.0",
    "ansible-navigator==26.8.0",
]

[dependency-groups]
dev = [
    "music-assistant",
]

[tool.uv.sources]
music-assistant = { git = "https://github.com/music-assistant/server.git", rev = "2.10.2" }

[tool.pyright]
venvPath = "."
venv = ".venv"
