---
- name: Restart mDNS aliases
  ansible.builtin.systemd_service:
    name: avahi-alias@{{ item }}.service
    daemon_reload: true
    state: restarted
  loop: "{{ caddy_aliases }}"
  listen: restart_avahi_aliases
