---
- name: Configure the loudest office raspi
  hosts: raspi
  become: true
  roles:
    # base setup of the pi
    - role: base
      vars:
        base_firewall_allow:
          - { port: 22, proto: tcp } # ssh
          - { port: 5353, proto: udp } # mDNS
          - { port: 8095, proto: tcp } # music assistant web ui
          - { port: 8097, proto: tcp } # music assistant stream server
    # music assistant as a rootless podman-compose service
    - role: music_assistant
