---
base_packages:
  - kitty-terminfo
  - vim
  - htop
  - du-dust
  - avahi-daemon
  - unattended-upgrades
  - needrestart

# cap systemd journal disk usage
base_journald_max_use: 200M

base_firewall_allow:
  - { port: 22, proto: tcp } # ssh
  - { port: 5353, proto: udp } # mDNS (avahi)

base_ssh_authorized_keys: []
