---
- name: Reload sshd
  ansible.builtin.service:
    name: ssh
    state: reloaded
  listen: reload_sshd

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  listen: restart_journald
